using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DeskApp.Migrations
{
    public partial class MuniFinancialProfile : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "muni_financial_profile",
                columns: table => new
                {
                    muni_financial_profile_id = table.Column<Guid>(nullable: false),
                    approval_id = table.Column<int>(nullable: false),
                    city_code = table.Column<int>(nullable: false),
                    created_by = table.Column<int>(nullable: false),
                    created_date = table.Column<DateTime>(nullable: false),
                    cycle_id = table.Column<int>(nullable: true),
                    deleted_by = table.Column<int>(nullable: true),
                    deleted_date = table.Column<DateTime>(nullable: true),
                    is_deleted = table.Column<bool>(nullable: false),
                    last_modified_by = table.Column<int>(nullable: true),
                    last_modified_date = table.Column<DateTime>(nullable: true),
                    mlgu2009_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2009_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2009_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2009_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2009_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2009_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2009_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2009_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2009_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2009_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2009_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2009_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2009_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2009_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2009_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2009_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2009_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2009_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2009_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2009_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2009_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2009_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2009_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2009_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2009_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2009_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2009_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2009_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2009_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2009_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2010_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2010_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2010_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2010_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2010_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2010_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2010_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2010_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2010_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2010_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2010_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2010_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2010_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2010_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2010_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2010_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2010_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2010_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2010_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2010_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2010_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2010_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2010_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2010_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2010_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2010_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2010_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2010_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2010_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2010_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2011_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2011_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2011_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2011_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2011_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2011_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2011_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2011_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2011_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2011_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2011_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2011_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2011_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2011_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2011_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2011_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2011_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2011_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2011_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2011_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2011_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2011_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2011_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2011_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2011_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2011_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2011_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2011_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2011_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2011_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2012_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2012_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2012_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2012_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2012_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2012_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2012_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2012_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2012_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2012_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2012_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2012_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2012_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2012_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2012_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2012_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2012_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2012_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2012_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2012_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2012_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2012_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2012_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2012_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2012_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2012_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2012_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2012_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2012_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2012_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2013_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2013_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2013_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2013_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2013_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2013_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2013_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2013_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2013_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2013_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2013_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2013_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2013_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2013_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2013_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2013_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2013_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2013_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2013_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2013_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2013_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2013_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2013_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2013_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2013_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2013_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2013_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2013_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2013_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2013_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2014_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2014_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2014_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2014_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2014_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2014_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2014_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2014_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2014_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2014_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2014_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2014_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2014_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2014_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2014_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2014_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2014_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2014_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2014_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2014_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2014_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2014_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2014_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2014_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2014_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2014_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2014_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2014_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2014_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2014_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2015_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2015_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2015_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2015_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2015_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2015_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2015_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2015_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2015_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2015_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2015_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2015_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2015_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2015_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2015_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2015_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2015_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2015_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2015_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2015_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2015_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2015_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2015_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2015_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2015_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2015_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2015_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2015_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2015_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2015_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2016_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2016_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2016_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2016_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2016_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2016_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2016_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2016_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2016_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2016_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2016_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2016_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2016_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2016_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2016_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2016_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2016_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2016_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2016_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2016_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2016_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2016_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2016_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2016_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2016_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2016_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2016_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2016_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2016_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2016_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2017_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2017_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2017_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2017_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2017_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2017_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2017_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2017_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2017_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2017_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2017_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2017_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2017_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2017_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2017_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2017_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2017_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2017_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2017_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2017_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2017_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2017_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2017_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2017_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2017_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2017_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2017_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2017_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2017_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2017_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2018_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2018_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2018_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2018_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2018_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2018_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2018_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2018_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2018_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2018_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2018_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2018_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2018_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2018_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2018_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2018_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2018_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2018_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2018_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2018_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2018_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2018_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2018_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2018_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2018_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2018_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2018_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2018_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2018_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2018_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    mlgu2019_ex_economic = table.Column<decimal>(nullable: true),
                    mlgu2019_ex_economic_source = table.Column<string>(nullable: true),
                    mlgu2019_ex_educ = table.Column<decimal>(nullable: true),
                    mlgu2019_ex_educ_source = table.Column<string>(nullable: true),
                    mlgu2019_ex_gen_public = table.Column<decimal>(nullable: true),
                    mlgu2019_ex_gen_public_source = table.Column<string>(nullable: true),
                    mlgu2019_ex_health = table.Column<decimal>(nullable: true),
                    mlgu2019_ex_health_source = table.Column<string>(nullable: true),
                    mlgu2019_ex_housing = table.Column<decimal>(nullable: true),
                    mlgu2019_ex_housing_source = table.Column<string>(nullable: true),
                    mlgu2019_ex_labor = table.Column<decimal>(nullable: true),
                    mlgu2019_ex_labor_source = table.Column<string>(nullable: true),
                    mlgu2019_ex_other_purposes = table.Column<decimal>(nullable: true),
                    mlgu2019_ex_other_purposes_source = table.Column<string>(nullable: true),
                    mlgu2019_ex_social_welfare = table.Column<decimal>(nullable: true),
                    mlgu2019_ex_social_welfare_source = table.Column<string>(nullable: true),
                    mlgu2019_rev_devt_fund = table.Column<decimal>(nullable: true),
                    mlgu2019_rev_devt_fund_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2019_rev_devt_fund_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2019_rev_devt_fund_source = table.Column<string>(nullable: true),
                    mlgu2019_rev_ira_share = table.Column<decimal>(nullable: true),
                    mlgu2019_rev_ira_share_source = table.Column<string>(nullable: true),
                    mlgu2019_rev_locally_sourced = table.Column<decimal>(nullable: true),
                    mlgu2019_rev_locally_sourced_source = table.Column<string>(nullable: true),
                    mlgu2019_rev_other_revenues_total = table.Column<decimal>(nullable: true),
                    mlgu2019_rev_other_revenues_total_source = table.Column<string>(nullable: true),
                    mlgu2019_rev_total_lgu_income = table.Column<decimal>(nullable: true),
                    mlgu2019_rev_total_lgu_income_per_capita = table.Column<decimal>(nullable: true),
                    mlgu2019_rev_total_lgu_income_per_capita_source = table.Column<string>(nullable: true),
                    mlgu2019_rev_total_lgu_income_source = table.Column<string>(nullable: true),
                    population_2015 = table.Column<int>(nullable: false),
                    prov_code = table.Column<int>(nullable: false),
                    push_date = table.Column<DateTime>(nullable: true),
                    push_status_id = table.Column<int>(nullable: false),
                    region_code = table.Column<int>(nullable: false),
                    talakayan_date_end = table.Column<DateTime>(nullable: true),
                    talakayan_date_start = table.Column<DateTime>(nullable: true),
                    talakayan_yr_id = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_muni_financial_profile", x => x.muni_financial_profile_id);
                    table.ForeignKey(
                        name: "FK_muni_financial_profile_lib_city_city_code",
                        column: x => x.city_code,
                        principalTable: "lib_city",
                        principalColumn: "city_code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_muni_financial_profile_lib_cycle_cycle_id",
                        column: x => x.cycle_id,
                        principalTable: "lib_cycle",
                        principalColumn: "cycle_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_muni_financial_profile_lib_province_prov_code",
                        column: x => x.prov_code,
                        principalTable: "lib_province",
                        principalColumn: "prov_code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_muni_financial_profile_lib_region_region_code",
                        column: x => x.region_code,
                        principalTable: "lib_region",
                        principalColumn: "region_code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_muni_financial_profile_talakayan_year_talakayan_yr_id",
                        column: x => x.talakayan_yr_id,
                        principalTable: "talakayan_year",
                        principalColumn: "talakayan_yr_id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_muni_financial_profile_city_code",
                table: "muni_financial_profile",
                column: "city_code");

            migrationBuilder.CreateIndex(
                name: "IX_muni_financial_profile_cycle_id",
                table: "muni_financial_profile",
                column: "cycle_id");

            migrationBuilder.CreateIndex(
                name: "IX_muni_financial_profile_prov_code",
                table: "muni_financial_profile",
                column: "prov_code");

            migrationBuilder.CreateIndex(
                name: "IX_muni_financial_profile_region_code",
                table: "muni_financial_profile",
                column: "region_code");

            migrationBuilder.CreateIndex(
                name: "IX_muni_financial_profile_talakayan_yr_id",
                table: "muni_financial_profile",
                column: "talakayan_yr_id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "muni_financial_profile");
        }
    }
}
